# Form implementation generated from reading ui file 'ui/TestSixth.ui'
#
# Created by: PyQt6 UI code generator 6.7.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_TestSixthForm(object):
    def setupUi(self, TestSixthForm):
        TestSixthForm.setObjectName("TestSixthForm")
        TestSixthForm.resize(650, 500)
        self.gridLayout = QtWidgets.QGridLayout(TestSixthForm)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(parent=TestSixthForm)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.gridLayout.addLayout(self.horizontalLayout_2, 5, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=TestSixthForm)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.label_2 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=TestSixthForm)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.gridLayout.addLayout(self.verticalLayout, 3, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem1, 6, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem2, 1, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem3, 5, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem4, 3, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem5, 4, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.gridLayout.addItem(spacerItem6, 2, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem7, 1, 2, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem8, 3, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.gridLayout.addItem(spacerItem9, 5, 2, 1, 1)

        self.retranslateUi(TestSixthForm)
        QtCore.QMetaObject.connectSlotsByName(TestSixthForm)

    def retranslateUi(self, TestSixthForm):
        _translate = QtCore.QCoreApplication.translate
        TestSixthForm.setWindowTitle(_translate("TestSixthForm", "TestSixth"))
        self.label_5.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-weight:696;\">Задача №6</span></p></body></html>"))
        self.label_9.setText(_translate("TestSixthForm", "00:00:00"))
        self.label.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Амбивалентность</span></p></body></html>"))
        self.label_2.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Рецептура</span></p></body></html>"))
        self.label_3.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Симпозиум</span></p></body></html>"))
        self.label_4.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Эквилибрист</span></p></body></html>"))
        self.label_6.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Интеллект</span></p></body></html>"))
        self.label_7.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Престиж</span></p></body></html>"))
        self.label_8.setText(_translate("TestSixthForm", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Космонавтика</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TestSixthForm = QtWidgets.QWidget()
    ui = Ui_TestSixthForm()
    ui.setupUi(TestSixthForm)
    TestSixthForm.show()
    sys.exit(app.exec())
